language: php

sudo: false

php:
  - 7.2

env:
  - RHO_TEST=unit
  - RHO_TEST=integration

matrix:
  fast_finish: true

before_script:

before_install:
  - travis_retry composer clear-cache

install:
  - travis_retry make "$RHO_TEST"-test-env
  - travis_retry composer dump-autoload # Dumps autoload-dev too 
  - php -r 'print_r(require("vendor/composer/autoload_psr4.php"));'

script:
  - make "$RHO_TEST"-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
